# Generated by Django 5.0.4 on 2024-12-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_is_active', models.BooleanField()),
                ('emp_is_manager', models.BooleanField(default=False)),
                ('emp_first_name', models.CharField(max_length=50)),
                ('emp_last_name', models.CharField(max_length=50)),
                ('emp_dob', models.DateField()),
                ('emp_start_date', models.DateField()),
            ],
        ),
    ]
