# Generated by Django 5.0.4 on 2024-12-06 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_is_complete', models.BooleanField()),
                ('job_name', models.CharField(max_length=200)),
                ('job_start', models.DateTimeField(auto_now_add=True)),
                ('job_end', models.DateTimeField()),
                ('job_lot', models.CharField(max_length=200)),
                ('job_batch', models.CharField(max_length=200)),
                ('job_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jobs.jobtype')),
            ],
        ),
    ]
