# Generated by Django 5.0.4 on 2024-12-06 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0003_tasklog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobtype',
            old_name='type_id',
            new_name='job_type_id',
        ),
        migrations.RenameField(
            model_name='jobtype',
            old_name='type_name',
            new_name='job_type_name',
        ),
        migrations.RenameField(
            model_name='tasklog',
            old_name='task_data',
            new_name='task_log_data',
        ),
        migrations.RenameField(
            model_name='tasklog',
            old_name='employee_id',
            new_name='task_log_employee_id',
        ),
        migrations.RenameField(
            model_name='tasklog',
            old_name='task_id',
            new_name='task_log_id',
        ),
        migrations.RenameField(
            model_name='tasklog',
            old_name='task_job',
            new_name='task_log_job',
        ),
        migrations.RenameField(
            model_name='tasklog',
            old_name='task_tstamp',
            new_name='task_log_tstamp',
        ),
        migrations.AddField(
            model_name='job',
            name='job_desc',
            field=models.CharField(default='null', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='job_batch',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_lot',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('task_type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('task_type_name', models.CharField(max_length=100)),
                ('task_type_desc', models.CharField(blank=True, max_length=500)),
                ('task_type_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jobs.jobtype')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_is_complete', models.BooleanField()),
                ('task_name', models.CharField(max_length=100)),
                ('task_desc', models.CharField(max_length=500)),
                ('task_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jobs.job')),
                ('task_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jobs.tasktype')),
            ],
        ),
    ]
